---
- name: Download repo mysql
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    state: present

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Create Mysql configuration file
  become: yes
  template: src=my.cnf.j2 dest=/root/.my.cnf mode=0600

- name: Create Mysql configuration file to ETC
  become: yes
  template: src=my.cnf.j2 dest=/etc/my.cnf mode=0600

- name: Start mysql.service
  become: yes
  shell: sudo systemctl restart mysqld && sudo systemctl enable mysqld

- name: Create a database to Wordpress
  mysql_db:
    name: db_desafio
  when:
    wordpress_mysql_enabled == true
  tags: desafio


- name: Create Wordpress user into MySQL
  mysql_user:
    name: desafio
    password: desafio
    priv: "db_desafio.*:ALL"
  when:
    wordpress_mysql_enabled == true
  tags: desafio


