---
- hosts: dbservers
  tasks: 
    - name: Download repo mysql
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
        state: present
    
    - name: Install Mysql package
      yum: name={{ item }} state=installed
      with_items:
       - mysql-server
       - MySQL-python
       - libselinux-python
       - libsemanage-python
    
    
    - name: Configure SELinux 
      seboolean: name=mysql_connect_any state=true persistent=yes
      when: sestatus.rc != 0
    
    - name: Create Mysql configuration file
      template: src=my.cnf.j2 dest=/etc/my.cnf
      notify: 
        - start mysql
        - enable mysql
      tags: mysql
    
    - name: insert iptables rule
      lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
                  insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
    
    - name: Create Application Database
      mysql_db: name={{ dbname }} state=present
    
    - name: Create Application DB User
      mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present