---
- name: yum update
  action: yum name=* state=latest

- name: install mysql
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mysql-server
    - mysql-client
  notify:
    - start mysql  

