---
- name: Download repo mysql
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    state: present

- name: initial repo
  shell: yum -ivh mysql-community-release-el7-5.noarch.rpm

- name: update
  shell: yum update

- name: install mysql
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - mysql-client
      - mysql-server
