---
- name: epel-release
  yum:
    name: epel-release
    state: present
    
- name: Install Nginx
  yum: 
    name: nginx #repositório do nginx para centos7
    state: present

- name: configuração do Nginx
  template: 
    src: confs-templates/nginx.conf.j2 
    dest: /etc/nginx/nginx.conf 
    mode: 0644 #permissão igual do desafio
  notify:
    - start nginx
  tags: nginx  