---
- name: install wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
    become: yes
  shell: systemctl restart nginx