---
- name: install wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz

- name: criar dir 
  file:
    path: /usr/share/nginx/html/wordpress
    state: directory

- name: Extract WordPress  
  become: yes
  unarchive:
    src: /tmp/wordpress.tar.gz    
    dest: /usr/share/nginx/html/wordpress/ #mando o arquivo para o diretório 
    copy: no

- name: start nginx
  become: yes
  shell: systemctl restart nginx
