---
- name: install wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz

- name: criar dir 
  file:
    path: /usr/share/nginx/html/wordpress
    state: directory

- name: Extract WordPress  
  become: yes
  unarchive:
    src: /tmp/wordpress.tar.gz    
    dest: /usr/share/nginx/html/wordpress/ #mando o arquivo para o diretório 
    copy: no

- name: criar file
  become: yes
  command: /usr/share/nginx/html/wordpress/wordpress/wp-config.php state=touch
  args:
    creates: /usr/share/nginx/html/wordpress/wordpress/wp-config.php

- name: configuração do wp
  become: yes
  template: 
    src: confs-templates/wp-config.php.j2 
    dest: /usr/share/nginx/html/wordpress/wordpress/wp-config.php 

- name: start nginx
  become: yes
  shell: systemctl restart nginx
