---
sudo: yes
Tasks:
  - name: Install Nginx e update centOS
    yum: 
      name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm #repositório do nginx para centos7
      state: present
      register: nginxinstalled

  - name: Quando a instalação do Nginx falhar
    when: nginxinstalled|failed
    fail: msg="nginx instalation failed, please check logs"

  - name: Pegar a configuração do Nginx
    when: nginxinstalled|success
    template: src=install-lamp/confs-templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 #permissão igual do desafio

  - name: checkar config do Nginx
    when: nginxinstalled|success
    command: /usr/sbin/nginx -t
    register: nginxconfig

  - name: nginx config error
    when: nginxconfig|failed
    fail: msg="A configuração do nginx está errada"