---
- name: yum update
  action: yum name=* state=latest

- name: yum install epel
  yum: name=epel-release.noarch state=latest

- name: download remi repo rpm
  get_url: url=http://rpms.remirepo.net/enterprise/remi-release-7.rpm dest=/root/ 

- name: install remi repo rpm
  yum: name=/root/remi-release-7.rpm state=present

- name: install php
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - php-msql
    - php-fpm