---
- name: download remi repo rpm
  get_url: 
    url: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
    dest: /root/ 

- name: install remi repo rpm
  yum: name=/root/remi-release-7.rpm state=present

- name: Active repo
  shell: yum-config-manager --enable remi-php70

- name: Install php
  yum: 
    name: php, php-mysql, php-fpm #install php

- name: configuração do php
  template: 
    src: confs-templates/www.conf.j2 
    dest: /etc/php-fpm.d/www.conf

- name: Start php-fpm.service
  become: yes
  shell: sudo systemctl restart php-fpm && sudo systemctl enable php-fpm