---
- name: start nginx
  become: yes
  service:
    name: nginx.service
    shell: systemctl start nginx
    enabled: yes

- name: restart nginx
  become: yes
  service:
    name: nginx
    shell: systemctl restart nginx
    enabled: yes